onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /conv_layer_1/DIN
add wave -noupdate /conv_layer_1/CLK
add wave -noupdate /conv_layer_1/RST
add wave -noupdate /conv_layer_1/DIS_STREAM
add wave -noupdate /conv_layer_1/EN_STREAM
add wave -noupdate /conv_layer_1/EN_STREAM_OUT_1
add wave -noupdate /conv_layer_1/VALID_OUT_1
add wave -noupdate /conv_layer_1/EN_LOC_STREAM_1
add wave -noupdate /conv_layer_1/DOUT_1_1
add wave -noupdate /conv_layer_1/DOUT_2_1
add wave -noupdate /conv_layer_1/DOUT_3_1
add wave -noupdate /conv_layer_1/DOUT_4_1
add wave -noupdate /conv_layer_1/DOUT_5_1
add wave -noupdate /conv_layer_1/DOUT_6_1
add wave -noupdate /conv_layer_1/DOUT_7_1
add wave -noupdate /conv_layer_1/DOUT_8_1
add wave -noupdate /conv_layer_1/DOUT_9_1
add wave -noupdate /conv_layer_1/DOUT_10_1
add wave -noupdate /conv_layer_1/INTERNAL_RST
add wave -noupdate /conv_layer_1/PIXEL_COUNT
add wave -noupdate /conv_layer_1/OUT_PIXEL_COUNT
add wave -noupdate /conv_layer_1/EN_NXT_LYR_1
add wave -noupdate /conv_layer_1/FRST_TIM_EN_1
add wave -noupdate /conv_layer_1/Enable_MULT
add wave -noupdate /conv_layer_1/DOUT_1_2
add wave -noupdate /conv_layer_1/DOUT_2_2
add wave -noupdate /conv_layer_1/DOUT_3_2
add wave -noupdate /conv_layer_1/DOUT_4_2
add wave -noupdate /conv_layer_1/DOUT_5_2
add wave -noupdate /conv_layer_1/DOUT_6_2
add wave -noupdate /conv_layer_1/DOUT_7_2
add wave -noupdate /conv_layer_1/DOUT_8_2
add wave -noupdate /conv_layer_1/DOUT_9_2
add wave -noupdate /conv_layer_1/DOUT_10_2
add wave -noupdate /conv_layer_1/EN_STREAM_OUT_2
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/CLK
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/RST
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/DIS_STREAM
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/EN_STREAM
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/EN_STREAM_OUT_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/VALID_OUT_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/EN_LOC_STREAM_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/DOUT_1_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/DOUT_2_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/DOUT_3_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/DOUT_4_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/DOUT_5_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/DOUT_6_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/DOUT_7_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/DOUT_8_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/DOUT_9_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/DOUT_10_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/INTERNAL_RST
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/VALID_NXTLYR_PIX
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/PIXEL_COUNT
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/OUT_PIXEL_COUNT
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/EN_NXT_LYR_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/FRST_TIM_EN_8
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/Enable_MULT
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/Enable_ADDER
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/Enable_ReLU
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/Enable_BIAS
add wave -noupdate /conv_layer_1/POOL_LYR_2/CONV_LYR_3/POOL_LYR_4/Flatten_LYR_5/FC_LYR_6/FC_LYR_7/FC_LYR_8/COUNT_PIX
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {232 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 742
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {508 ps}